# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-vbguest")
  raise "please run 'vagrant plugin install vagrant-vbguest'"
end

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/centos7"

  #config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 10081, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.36.104"

  #ホスト側ソースの場所に合わせてディレクトリを変更して下さい(ゲスト側は変更不要)
  config.vm.synced_folder "../src", "/home/vagrant/screwdriver", type:"virtualbox", create: true, mount_options:['dmode=777','fmode=777']

  #vagrantファイル(変更不要)
  config.vm.synced_folder ".", "/vagrant", type:"virtualbox"

  config.vm.provider "virtualbox" do |vb|
      # vb.memory = "2048"
      # Display the VirtualBox GUI when booting the machine
      # vb.gui = true
  end

end
